abstract: Strawberry Perl for win32
author: David A Golden <dagolden@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Perl-Dist-Strawberry
no_index: 
  directory: 
    - extra
    - bin
    - inc
    - t
requires: 
  Perl::Dist::Builder: 0.0.4
version: 0.1.2
