---
abstract: 'Strawberry Perl for win32'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Path: 2.04
  File::Remove: 1.42
  File::Spec: 3.2701
  LWP::Online: 1.07
  Test::More: 0.42
  URI::file: 1.37
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::Strawberry
name: Perl-Dist-Strawberry
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Archive::Zip: 1.26
  Object::Tiny: 1.06
  Perl::Dist: 1.11
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.08
