---
abstract: 'Strawberry Perl for win32'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Path: 2.04
  File::Remove: 1.42
  File::Spec: 3.2701
  LWP::Online: 1.07
  Test::More: 0.42
  Test::Perl::Dist: 0.202
  URI::file: 4.20
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::Strawberry
name: Perl-Dist-Strawberry
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Perl::Dist::WiX: 1.102
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 2.02_01
