---
abstract: 'Strawberry Perl for win32'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Path: 2.04
  File::Remove: 1.42
  File::Spec: 3.2701
  LWP::Online: 1.07
  Test::More: 0.42
  URI::file: 1.37
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.83'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::Strawberry
name: Perl-Dist-Strawberry
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Perl::Dist: 1.14
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Perl-Dist-Strawberry
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist-Strawberry
version: 1.11
